# Global Variables
@accentColor = #007acc
@selectionBackground = #e3f1fa

# Color Overrides (Hex formats: #RGB, #RGBA, #RRGGBB, #RRGGBBAA)
Panel.background = #ffffff
Label.foreground = #333333

# Component Specifics
Button.arc = 9
Button.background = @accentColor
Button.foreground = #999999
Button.focusedBackground = darken(@accentColor, 10%)

# Text Component Styles
TextField.placeholderForeground = #999999
TextField.arc = 4

# Using Variables and Functions
TableHeader.separatorColor = darken($TableHeader.background, 10%)

# In .properties file
[style]Button.primary = background: #08f; foreground: #fff

